RECENT_CASES = [
    {
        "id": "case-001",
        "age": 67,
        "gender": "Male",
        "condition": "Acute Coronary Syndrome",
        "confidence": 0.9234,
        "risk_level": "Critical",
        "created_at": "2024-12-15T08:30:00Z",
    },
    {
        "id": "case-002",
        "age": 45,
        "gender": "Female",
        "condition": "Community-Acquired Pneumonia",
        "confidence": 0.8876,
        "risk_level": "High",
        "created_at": "2024-12-15T09:15:00Z",
    },
    {
        "id": "case-003",
        "age": 52,
        "gender": "Male",
        "condition": "Type 2 Diabetes - Uncontrolled",
        "confidence": 0.9102,
        "risk_level": "High",
        "created_at": "2024-12-15T10:00:00Z",
    },
    {
        "id": "case-004",
        "age": 38,
        "gender": "Female",
        "condition": "Migraine with Aura",
        "confidence": 0.8543,
        "risk_level": "Moderate",
        "created_at": "2024-12-15T10:45:00Z",
    },
    {
        "id": "case-005",
        "age": 71,
        "gender": "Male",
        "condition": "Congestive Heart Failure",
        "confidence": 0.9401,
        "risk_level": "Critical",
        "created_at": "2024-12-15T11:30:00Z",
    },
    {
        "id": "case-006",
        "age": 29,
        "gender": "Female",
        "condition": "Acute Viral Infection",
        "confidence": 0.7892,
        "risk_level": "Low",
        "created_at": "2024-12-15T12:00:00Z",
    },
    {
        "id": "case-007",
        "age": 58,
        "gender": "Male",
        "condition": "COPD Exacerbation",
        "confidence": 0.8765,
        "risk_level": "High",
        "created_at": "2024-12-15T13:15:00Z",
    },
    {
        "id": "case-008",
        "age": 43,
        "gender": "Female",
        "condition": "Hypertensive Crisis",
        "confidence": 0.9056,
        "risk_level": "Critical",
        "created_at": "2024-12-15T14:00:00Z",
    },
]
