# Generated by Django 4.2.5 on 2025-05-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_designation_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
