# Generated by Django 5.2 on 2025-06-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_portfolio_address_remove_portfolio_cgpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='resume',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='fatherName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='motherName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='parentContact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pucBoard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pucCollege',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pucPercentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pucYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sem1_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sem2_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sem3_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sem4_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sem5_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sem6_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sem7_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='sem8_sgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='semester',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='studentName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tenthBoard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tenthPercentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tenthSchool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tenthYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='usn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
