# Generated by Django 4.2.11 on 2025-06-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_portfolio_address_portfolio_cgpa_portfolio_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
